name: lost_mate
description: Aplikasi Lost & Found Barang Hilang berbasis Flutter.

# Versi aplikasi, ubah jika perlu
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management & utility
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1

  # Database lokal
  sqflite: ^2.3.3+1
  path: ^1.8.3

  # HTTP/REST API
  http: ^1.2.1
  url_launcher: ^6.2.6

  # UI
  flutter_svg: ^2.0.9

  # Camera/Image Picker
  image_picker: ^1.1.1

  # Maps & Location
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  location: ^6.0.2

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.3

  # Animasi (opsional)
  flutter_spinkit: ^5.2.0

  #Salin ke clipboard
  clipboard: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/logo.png
    # Tambah folder assets jika nanti butuh gambar/logo
